apiVersion: prefs/v1beta1
kind: PrefDefaults                    # Convention: CamelCase for kinds
metadata:
  name: global-preferences            # Added name as it's required in K8s
  domain: GlobalPreferences
  labels:                            # Moved labels to metadata
    macos-version: sequoia
spec:
  preferences:
  - name: AppleLanguage
    kind: language
    metadata:                        # Each sub-resource gets its own metadata
      labels:
        what-sets: install
        preference-type: language
  - name: AppleLocale
    kind: locale
    metadata:
      labels:
        what-sets: install
        preference-type: locale